
#SELECCIONAR NUESTRA IMAGEN DE DODCKER A USAR
FROM python:3.12.0a6-alpine3.17

#MOSTRAR LOS LOGS QUE MANDA DJANGO CUANDO ES NECESARIO HACER MIGRACIONES
ENV PYTHONUNBUFFERED=1

# SELECCIONAMOS NUESTRO WORKING DIRECTORY
WORKDIR /app

#RUN OERMITE EJECUTAR COMANDOS DENTRO DEL CONTENEDOR
#EN ESTE CASO ACTUALIZAMOS E INSTALAMOS ALGUNOS PAQUETES NECESARIOS
RUN apk update \
    && apk add --no-cache gcc musl-dev postgresql-dev python3-dev libffi-dev \
    && pip install --upgrade pip

#COPIAMOS LOS ARCHIVOS NECESARIOS PARA PREPARAR EL EQUIPO EN EL WORKING DIRECCTORY
COPY ./requirements.txt ./

RUN pip install -r requirements.txt

#COPIAR TODO Y EGARLO EN EL WORKING DIRECTORY
COPY ./ ./

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]